import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { TRPCReactProvider } from "@/trpc/react";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

import Providers from "@/app/_components/Providers";
import Nav from "@/app/_components/Nav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body >
          <TRPCReactProvider cookies={cookies().toString()}>
            <Providers>

            <main vaul-drawer-wrapper="" className="text-foreground bg-background mx-auto flex-grow ">
            <Nav />
              <section className="max-w-screen-2xl px-5 mx-auto flex-grow">
                {children}
              </section>
            </main>

            </Providers>
          </TRPCReactProvider>
      </body>
    </html>
  );
}
